config:
    string: value on config
    list:
        - first value
        - second value
    map:
        firstKey: value1
        secondKey:
            innerKey1: innerValue1
            innerKey2: innerValue2
    inner:
        number: 10
        valid: true
