# Autocreate DB on startup
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.show_sql: false


# Spring data config

# Uncomment to use a file instead of embedded
#spring.datasource.url: jdbc:h2:file:./h2db

# Other properties

#spring.datasource.username: dbuser
#spring.datasource.password: dbpass